/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
	uint32_t *pClkCtrlReg = (uint32_t*)0x4002104C;
	uint32_t *pPortBModeReg = (uint32_t*)0x48000400;
	uint32_t *pPortBOutReg = (uint32_t*)0x48000414;

	uint32_t *pPortCModeReg = (uint32_t*)0x48000800;
	uint32_t *pPortCInReg = (uint32_t*)0x48000810;

	// Enable the clock for GPOIB, GPOIC peripheral in the AHB1ENR
	*pClkCtrlReg |= (1<<1);
	*pClkCtrlReg |= (1<<2);


	// Configuring PD12 as output, p.304
	*pPortBModeReg &= ~(3<<24);
	// b. make 24th bit position as 1(set)
	*pPortBModeReg |= (1<<24);


	// Configure PC13 as input (GPOIC mode register)
	*pPortCModeReg &= ~(3<<26);

	while(1){
		// Read the pin status of the PA0 (GPOIA input data register)
		uint8_t pinStatus = (uint8_t)(*pPortCInReg & 0x1);	// zero out all other bits except bit 0

		if (pinStatus){
			// turn on the LED
			*pPortBOutReg |= (1<<12);
		}else{
			*pPortBOutReg &= ~(1<<12);
		}
	}

}
