/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
	uint32_t *pClkCtrlReg = (uint32_t*)0x4002104C;
	uint32_t *pPortBModeReg = (uint32_t*)0x48000400;
	uint32_t *pPortBOutReg = (uint32_t*)0x48000414;

	// 1. Enable the clock for GPOIB peripheral in the AHB1ENR
	*pClkCtrlReg |= (1<<1);


	// 2. Configure the mode of the IO pin as output
	// a. clear the 28th and 29th bit positions, p.304
	*pPortBModeReg &= ~(3<<28);
	// b. make 28th bit position as 1(set)
	*pPortBModeReg |= (1<<28);

	while (1){
		// 3. Set 14th bit of the output data register to make I/O pin-14 as High
		*pPortBOutReg |= (1<<14);
		// Introduce small human observable delay
		// This loop executes for 10k times
		for (uint32_t i=0; i<10000; i++);
		*pPortBOutReg &= ~(1<<14);
		for (uint32_t i=0; i<10000; i++);
	}

}
