/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "main.h"
#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
	RCC_AHB1ENR_t volatile *const pClkCtrlReg   = ADDR_REG_AHB1ENR;
	GPIOx_MODE_t  volatile *const pPortBModeReg = ADDR_REG_GPIOB_MODE;
	GPIOx_ODR_t   volatile *const pPortBOutReg  = ADDR_REG_GPIOB_OD;

	//1. enable the clock for GPOID peripheral in the AHB1ENR (SET the 3rd bit position)
	pClkCtrlReg->gpiob_en = CLOCK_ENABLE;


	//2. configure the mode of the IO pin as output
	pPortBModeReg->pin_14 = MODE_CONF_OUTPUT;

	while(1)
	{
		//Set 12th bit of the output data register to make I/O pin-12 as HIGH
		pPortBOutReg->pin_14  = PIN_STATE_HIGH;

		//introduce small human observable delay
		//This loop executes for 300K times
		for(uint32_t i=0 ; i < DELAY_COUNT ; i++ );

		//Reset 12th bit of the output data register to make I/O pin-12 as LOW
		pPortBOutReg->pin_14  = PIN_STATE_LOW;

		for(uint32_t i=0 ; i < 300000 ; i++ );
	}

    /* Loop forever */
	for(;;);
}
